### ISSUE TITLE
Pasting comma-separated tags

### ISSUE THREAD

**Issue by prokr** [markashleybell/MAB.Bootstrap.TagInput#12]
First I would like to thank you for the best autocomplete script I have found on internet!

I just have one question or a request for feature, is it possible to PASTE (CTRL+V) coma-separated values to INPUT field?
For example if I want to copy all tags from somewhere else, I got string in my clipboard:
Orange, Apple, Pear
If I paste it in script it creates one single tag "Orange, Apple, Pear", 
but three separate tags are required.
Please see in example below:
![example](https://user-images.githubusercontent.com/33546590/109377543-bd581b80-78d4-11eb-9b15-9c1105b2962e.png)

Thank you!

**Comment by markashleybell** [comment]
I'm really glad you are finding this useful; I wrote it to use in my own apps so it's quite specific to my needs, but if others can make use of it too, great!

Anyway, this sounds like a good suggestion to me. Please feel free to submit a PR if you have an idea of how it should work, otherwise I will definitely look into it as soon as I get a bit of time.

**Comment by prokr** [comment]
I started to investigate your script more closely and have found out that the version here on Github is very different from what I have downloaded from https://www.jqueryscript.net/demo/jQuery-Tags-Input-Plugin-with-Autocomplete-Support-Mab-Tag-Input/

In version on jqueryscript JavaScript is being used.
In version GitHub TrueScript is being used.

I would like to improve the JavaScript version, which cannot be found here anymore, right?

**Comment by markashleybell** [comment]
Ah—I did wonder how you found this! 

I don't know what that site you've linked to is, it looks like they just scraped a really old version of the previous incarnation of this library without my permission.

Anyway, if you want the source code for _that_, it's here: https://github.com/markashleybell/mab.jquery.taginput

I don't maintain that repository any more, but it's MIT-licensed (as it this one), so please feel free to fork it and improve as you wish.

**Comment by markashleybell** [comment]
This is in place now (see a52207d).
